kind: ConfigMap
apiVersion: v1
metadata:
  name: default-clusterscanprofiles
  namespace: {{ template "app.namespace" . }}
data:
  # Default ClusterScanProfiles per cluster provider type
  # Default ClusterScanProfiles per cluster provider type
  rke2: "rke2-cis-1.9-profile"
  eks: "eks-profile-1.5.0"
  gke: "gke-profile-1.6.0"
  aks: "aks-profile"
  k3s: "k3s-cis-1.9-profile"
  default: "cis-1.9-profile"
