---
apiVersion: compliance.cattle.io/v1
kind: ClusterScanProfile
metadata:
  name: eks-profile-1.5.0
  annotations:
    clusterscanprofile.compliance.cattle.io/builtin: "true"
spec:
  benchmarkVersion: eks-1.5.0
